FROM python:3.13-slim

# cria diretório de trabalho
WORKDIR /app

# instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copia o código
COPY . .

# expõe porta interna
EXPOSE 8000

# comando para rodar a API
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
